import type { EngineSettings } from "@/utils/engines";
import type { StrengthPreset } from "@/utils/engineStrength";

// Converted from Rodent II's bundled personality files (personalities/<group>/<name>.txt),
// each a curated list of eval-weight/search-limit overrides rather than a single Elo dial.
// Book file options are dropped since they reference paths relative to Rodent II's own
// install layout, which may not exist alongside the copied binary.
function personality(options: [string, string | number][]): EngineSettings {
    return options.map(([name, value]) => ({ name, value }));
}

export const rodentIIPresets: StrengthPreset[] = [
    {
        id: "rodentII-frank",
        name: "Frank (School)",
        elo: 1408,
        description: "Weak, rushes forward",
        options: personality([
            ["KingTropism", 100],
            ["OwnMobility", 100],
            ["OppMobility", 100],
            ["Forwardness", 100],
            ["PstStyle", 2],
            ["NpsLimit", 88],
            ["EvalBlur", 36],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-amy",
        name: "Amy (School)",
        elo: 1439,
        description: "Weak, aggressive, slow",
        options: personality([
            ["OwnAttack", 200],
            ["OppAttack", 100],
            ["OwnMobility", 200],
            ["OppMobility", 100],
            ["NpsLimit", 64],
            ["EvalBlur", 48],
            ["SlowMover", 150],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-chris",
        name: "Chris (School)",
        elo: 1474,
        description: "Weak, classical piece-square tables and restraint",
        options: personality([
            ["OwnAttack", 100],
            ["OppAttack", 100],
            ["OwnMobility", 100],
            ["OppMobility", 120],
            ["NpsLimit", 72],
            ["EvalBlur", 48],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-mark",
        name: "Mark (Club)",
        elo: 1500,
        description: "Defensive player who likes his own mobility",
        options: personality([
            ["OwnAttack", 100],
            ["OppAttack", 120],
            ["OwnMobility", 120],
            ["OppMobility", 100],
            ["NpsLimit", 450],
            ["EvalBlur", 50],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-dory",
        name: "Dory (School)",
        elo: 1540,
        description: "Weak, defense oriented",
        options: personality([
            ["OwnAttack", 100],
            ["OppAttack", 150],
            ["OwnMobility", 100],
            ["OppMobility", 150],
            ["MobilityStyle", 1],
            ["NpsLimit", 88],
            ["EvalBlur", 36],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-ben",
        name: "Ben (School)",
        elo: 1635,
        description: "Weak, balanced, precise evaluation for his strength range",
        options: personality([
            ["OwnAttack", 100],
            ["OppAttack", 100],
            ["OwnMobility", 100],
            ["OppMobility", 100],
            ["NpsLimit", 64],
            ["EvalBlur", 24],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-arthur",
        name: "Arthur (League)",
        elo: 1991,
        description: "Sub-2000 player, likes attack and restraint, slow thinker",
        options: personality([
            ["OwnAttack", 120],
            ["OppAttack", 100],
            ["OwnMobility", 100],
            ["OppMobility", 120],
            ["PawnStructure", 120],
            ["Outposts", 120],
            ["MobilityStyle", 1],
            ["NpsLimit", 3000],
            ["EvalBlur", 0],
            ["SlowMover", 120],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-theresa",
        name: "Theresa (League)",
        elo: 2100,
        description: "Tricky, likes positional compensation for material, unusual openings",
        options: personality([
            ["Material", 90],
            ["OwnAttack", 50],
            ["OppAttack", 70],
            ["OwnMobility", 120],
            ["OppMobility", 100],
            ["PiecePressure", 150],
            ["Lines", 105],
            ["Outposts", 110],
            ["NpsLimit", 5500],
            ["EvalBlur", 0],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-victor",
        name: "Victor (Masters)",
        elo: 2250,
        description: "Violent player who likes to sacrifice and plays gambits",
        options: personality([
            ["Material", 90],
            ["OwnAttack", 120],
            ["OppAttack", 100],
            ["OwnMobility", 120],
            ["OppMobility", 100],
            ["KingTropism", 50],
            ["Lines", 120],
            ["Forwardness", 50],
            ["PstStyle", 2],
            ["NpsLimit", 28000],
            ["EvalBlur", 0],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
    {
        id: "rodentII-nancy",
        name: "Nancy (Masters)",
        elo: 2300,
        description: "Attacking player who likes closed positions",
        options: personality([
            ["OwnAttack", 120],
            ["OppAttack", 100],
            ["OwnMobility", 100],
            ["OppMobility", 120],
            ["KnightLikesClosed", 8],
            ["Outposts", 120],
            ["NpsLimit", 30000],
            ["EvalBlur", 0],
            ["SlowMover", 100],
            ["Selectivity", 175],
        ]),
    },
];
